import type { Metadata } from "next";
import { Inter, Crimson_Text } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const crimson = Crimson_Text({
    subsets: ["latin"],
    weight: "400",
    variable: "--font-crimson",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${crimson.variable} ${inter.className}`}>
                {children}
            </body>
        </html>
    );
}
